### ISSUE TITLE
Feature Request: grep runtimepath & scriptnames

### ISSUE THREAD

**Issue by jyscao** [tpope/vim-scriptease#48] opened 2019-12-03 13:05 UTC
Hi tpope, I wrote [a small plugin](https://github.com/jyscao/vim-greprtpscr/) that greps through `&rtp` & `scriptnames`, which I've found useful for hacking on vim.

When I shared it on r/vim, it was suggested to me that I should turn it into a PR for scriptease, which makes sense to me, especially since I used a couple of your functions (`scriptease#capture` & `scriptease#scriptnames_qflist`) anyway.

So if you think these 2 features are good additions, just let me know.

**Comment by tpope** [comment] 2019-12-06 18:29
Duplicate of #46. I do like your `:scriptnames` variant, which sidesteps a lot of the challenges mentioned there. Not as big of fan of your grep replacements fixation, with their alternative regexp syntaxes and highly exaggerated performance improvements.

**Closed by tpope** 2019-12-06 18:29 UTC
